server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Запрещаем скрытые файлы и директории:
    # .env, .git, .aws, .vscode, .svn и т.д.
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Запрещаем типичные чувствительные файлы,
    # чтобы они не попадали в SPA fallback.
    location ~* \.(env|bak|old|sql|log)$ {
        deny all;
    }

    # Запрещаем очевидные конфигурационные файлы.
    location ~* ^/(docker-compose(\..*)?|Dockerfile|phpinfo)$ {
        deny all;
    }

    # React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}
